"""MicroDuck robot model specifications."""

from .model_variants import (
    MICRODUCK_BACKLASH_ROBOT_CFG,
    MICRODUCK_BALL_CFG,
    MICRODUCK_GROUND_PICK_ROBOT_CFG,
    MICRODUCK_ROLLERS_BACKLASH_ROBOT_CFG,
    MICRODUCK_STANDUP_ROBOT_CFG,
    MICRODUCK_WALK_BACKLASH_ROBOT_CFG,
    MICRODUCK_WALK_ROBOT_CFG,
    MICRODUCK_WALK_ROLLERS_ROBOT_CFG,
    SERVO_JOINT_NAMES,
)

__all__ = [
    "MICRODUCK_BACKLASH_ROBOT_CFG",
    "MICRODUCK_BALL_CFG",
    "MICRODUCK_GROUND_PICK_ROBOT_CFG",
    "MICRODUCK_ROLLERS_BACKLASH_ROBOT_CFG",
    "MICRODUCK_STANDUP_ROBOT_CFG",
    "MICRODUCK_WALK_BACKLASH_ROBOT_CFG",
    "MICRODUCK_WALK_ROBOT_CFG",
    "MICRODUCK_WALK_ROLLERS_ROBOT_CFG",
    "SERVO_JOINT_NAMES",
]
